name: sf CI
on:
  push:
    branches:
      - deploy-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: ls -l
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist'      # optional: defaults to entire repository

      - run: |
          curl --location --request GET 'localhost:8000/api/v3/stores/new-client-deploy-statuses' \
          --header 'Authorization: Basic MTox' \
          --header 'Content-Type: application/json' \
          --data-raw '{ \
            "snippet": "<script src=\"https://cdn.bundleb2b.net/js/v222.js\"></script> ", \
            "revision": "v220323" \
          }'