name: sf CI
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'apps/storefront/dist/assets'
      - name: create revision
        run: |
          poly_js=$(find apps/storefront/dist/assets -name polyfills-legacy.*.js -type f -printf '%f')
          index_js=$(find apps/storefront/dist/assets -name index-legacy.*.js -type f -printf '%f')
          curl --location --request POST ${{ secrets.API_HOST }}'/api/v3/stores/revisions' \
          --header 'Authorization: Basic '${{ secrets.API_CREDENTIAL }} \
          --header 'Content-Type: application/json' \
          --data-binary @- << EOF
          {
            "jsFiles": ["${{ secrets.S3_HOST }}/${poly_js}", "${{ secrets.S3_HOST }}/${index_js}"],
            "revisionTitle": "${GITHUB_SHA_SHORT}"
          }
          EOF
        shell: bash
      - name: start deploy
        run: |
          curl --location --request POST ${{ secrets.API_HOST }}'/api/v3/stores/deployments' \
          --header 'Authorization: Basic '${{ secrets.API_CREDENTIAL }} \
          --header 'Content-Type: application/json' \
          --data-binary @- << EOF
          {
            "deploy_all": true,
            "revision": "${GITHUB_SHA_SHORT}"
          }
          EOF
        shell: bash

