name: sf CI
on:
  push:
    branches:
      - deploy-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'   # optional: defaults to us-east-1
          SOURCE_DIR: 'apps/storefront/dist/assets'      # optional: defaults to entire repository


      - run: |
          index_css=$(find apps/storefront/dist/assets -name index.*.css -type f -printf '%f')
          poly_js=$(find apps/storefront/dist/assets -name polyfills-legacy.*.js -type f -printf '%f')
          index_js=$(find apps/storefront/dist/assets -name index-legacy.*.js -type f -printf '%f')
          api_host=https://dde1-2409-8a62-1374-dfd0-9053-8899-2542-18b8.ap.ngrok.io
          s3_host=https://b3-newsf-testtest.s3.us-west-2.amazonaws.com
          curl --location --request POST ${api_host}'/api/v3/stores/revisions' \
          --header 'Authorization: Basic '${{secrets.API_CREDENTIAL}} \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "cssFiles": ["'${s3_host}/${index_css}'"],
            "jsFiles": ["'${s3_host}/${poly_js}'", "'${s3_host}/${index_js}'"],
            "revisionTitle": "v220323"
          }'
        shell: bash

